### ISSUE TITLE
[bug] SMB SessionError: STATUS_PIPE_DISCONNECTED

### ISSUE THREAD

**Issue by jsdhasfedssad** [p0dalirius/Coercer#12]
Hi,

I love your tool and I have used it a lot! However, today during testing in my AD lab I suddenly get the error "SMB SessionError: STATUS_PIPE_DISCONNECTED" when attempting to coerce anonymously. 

Anonymous coercing has worked before. If I try authenticated coercing against the same DC it partially works. Also note that coercing using MS-RPRN.exe, and I assume authentication via Kerberos, against the same DC still works... As you can see the pipe LSARPC is accessible. 

Restarting dc1.adlab.local (10.0.0.200) does not help.

<img width="1114" alt="coerce1" src="https://user-images.githubusercontent.com/97032878/185759134-23ffc58a-d513-400e-b89b-0c5f59fe5eb3.png">

<img width="1253" alt="coerce3" src="https://user-images.githubusercontent.com/97032878/185759140-d8ad98c3-19d8-4c2f-b45c-ac23228908ca.png">

<img width="744" alt="coerce2" src="https://user-images.githubusercontent.com/97032878/185759144-4a9d285d-89fe-49a8-aa6d-ef9dcad49af4.png">

**Comment by p0dalirius** [comment]
Hi @jsdhasfedssad,

Thanks for reporting this bug. It's indeed not supposed to happen and I'll take care of it soon!

Best regards,
