### ISSUE TITLE
Add SpoolSample

### ISSUE THREAD

**Issue by Acebond** [p0dalirius/Coercer#5]
Amazing tool.

I didn't see SpoolSample in the list which could be useful to add. 

Some implementation are below:

https://github.com/dirkjanm/krbrelayx/blob/master/printerbug.py
https://github.com/BeetleChunks/SpoolSploit
https://gist.github.com/3xocyte/cfaf8a34f76569a8251bde65fe69dccc

**Comment by p0dalirius** [comment]
Thanks, It was already in the plans to add it ;) I'll do it soon!
