### ISSUE TITLE
[bug] Got "too many values to unpack" while trying to scan

### ISSUE THREAD

**Issue by b3qkc** [p0dalirius/Coercer#65]
The problem is in rpc.py:26
_transport, dst = binding.split(":")
one of binding was "ncalrpc:[PRRUniversal#4FAF6D748C97387A:3684]" what causes that error
Fixed with limiting split func to 1 occurence: _transport, dst = binding.split(":", 1)

**Comment by p0dalirius** [comment]
Problem is located here

https://github.com/p0dalirius/Coercer/blob/1ba95b2377103cf109cdf4fc9275df0cdfcb65f9/coercer/network/rpc.py#L26
