### ISSUE TITLE
[enhancement] JSON or XLSX report only contains results from last target in `scan` mode

### ISSUE THREAD

**Issue by AdrianVollmer** [p0dalirius/Coercer#70]
When specifying `--export-json` or `--export-xlsx` in `scan` mode, then the result of the `reporter` object is written to the same file after scanning each target, overwriting the previous result. We would either need to change the file name for each target, or - probably a better solution 0 `report_test_result` needs to take a keyword argument such as `target`.

The problem does not exist for `--export-sqlite`.

**Comment by p0dalirius** [comment]
Hey!

Thank you, perfect fix!
Merging
