### ISSUE TITLE
[enhancement] Possible inclusion for id_rsa private keys ?

### ISSUE THREAD

**Issue by Shellshock9001** [p0dalirius/Coercer#72]
A great addition would be adding id_rsa keys this way in case you don’t have the password.

**Comment by p0dalirius** [comment]
Hi!

You mean connecting to an account with certificates ?

**Comment by Shellshock9001** [comment]
> Hi!
> 
> You mean connecting to an account with certificates ?

When you find a private key and get an id_rsa key. That allows you to ssh without a password.

if we could use this tool without a password and use an id_rsa key

**Comment by p0dalirius** [comment]
Hi,

Coercer can already be used with LM or NT or both hashes, as stated in the help message:

```
  --hashes [LMHASH]:NTHASH
                        NT/LM hashes (LM hash can be empty)
```

I'm assuming you want to connect with a PFX certificate as stored in `ms-DS-KeyCredentialLink`, I'll add this

Best regards,
