### ISSUE TITLE
[bug] Blank line in target file crashes coercer

### ISSUE THREAD

**Issue by Dfte** [p0dalirius/Coercer#84]
Hey mate!

Small issue to notify that if you submit an invalid IP (here a blank line), coerce will crash:
![image](https://github.com/user-attachments/assets/3a948040-eca4-4332-b21d-1ab3a06f7371)

Nothing huge, probably a missing if username:, will try to push a fix ASAP :)

**Comment by p0dalirius** [comment]
Fixed :)
